Added Readme.md file
pablor83/CzatForLAN pull request #2
Opened 2019-11-13 20:45 UTC by pablor83

Please, check my Readme.md file

2019-11-14 18:34 UTC, krzysztofradomski commented
Something wrong with formatting, have a look: https://github.com/pablor83/CzatForLAN/tree/readme

2019-11-14 18:36 UTC, krzysztofradomski requested changes
Fix screenshots.

2019-11-18 19:26 UTC, pablor83 commented
OK, It's works. Check, is it now properly? Do you have any else suggestions?

2019-11-23 19:58 UTC, krzysztofradomski approved these changes

2019-11-25 17:22 UTC, merged